### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by remirobert** [robertdimarco/passport-google-token#10]
Hello,

I got an `Unauthorised` response.

This is my current code : 

``` javascript
var GoogleTokenStrategy = require('passport-google-token');

passport.use(new GoogleTokenStrategy.Strategy({
    clientID: "521119",
    clientSecret: "GuIbP6"
  },
  function(accessToken, refreshToken, profile, done) {
    console.log("profile google : " + profile);
    return done(null, null);
  }
));

app.get('/auth/google/token', passport.authenticate('google-token'),
 function(req, res) {
   console.log("user : " + req.user);
  res.send(req.user);
});
```

I don't know where is the problem. Can you help me.

**Comment by robertdimarco** [comment]
Try validating your token against `https://www.googleapis.com/oauth2/v1/tokeninfoaccess_token=<token>`, and make sure that you're including the token on the request by logging `req.params` to see if the `access_token` field is populated appropriately.

**Comment by oreporan** [comment]
Hi,
Having the same problem, validating against googleapi.com works, but using the library returns 401, I've tried GET and POST, wireshark shows that the access_token field is sent to my backend.

Where  do you suggest logging req.params? 
```
passport.use(new GoogleTokenStrategy({
    clientID:     Constants.GOOGLE_CLIENT_ID,
    clientSecret: Constants.GOOGLE_CLIENT_SECRET
  },
  function(accessToken, refreshToken, profile, done) {
    authenticateViaSocialNetwork(accessToken, profile, done, Constants.AUTHENTICATION_METHOD_GOOGLE);
  }
));
```

**Comment by oreporan** [comment]
From a bit of debugging, it looks like the the method 
`GoogleTokenStrategy.prototype.authenticate = function(req, options);` is being called twice, because when I log the return of `_loadUserProfile` I get first my expected result, and an undefined object which probably causes the error...
