### ISSUE TITLE
401 Unauthorized all the time from Postman with Token verified and sent as either headers or params

### ISSUE THREAD

**Issue by sebastiangug** [robertdimarco/passport-google-token#22]
I have a backend REST API built with Node + Express + Passport and I'm trying to authenticate using a google access token. I am using this strategy.

I have looked through the package's documentation and issues on github but there was nothing that fixed the issue.

I have verified the access token against:

https://www.googleapis.com/oauth2/v1/tokeninfo?idToken with the id Token and https://www.googleapis.com/oauth2/v1/tokeninfo?acessToken with the access token and both are valid but none of them work. I have double-triple checked that I'm using the correct clientID and secret on the backend and on the frontend I get the token from.

Here's the relevant code:

```
> 
> app.use(passport.initialize());
> passport.use(
>   new GoogleTokenStrategy(
>     {
>       clientID: config.get('google.clientID'),
>       clientSecret: config.get('google.clientSecret')
>     },
>     function(accessToken, refreshToken, profile, done) {
>       User.findOrCreate({ googleId: profile.id }, function(err, user) {
>         return done(err, user);
>       });
>     }
>   )
> );
> 
> app.use('/user', passport.authenticate('google-token'), userRoute);
```

and I am importing at the top as follows:
```

const passport = require('passport');
const GoogleTokenStrategy = require('passport-google-token').Strategy;
```

The app isn't throwing out any kind of errors.

**Comment by sebastiangug** [comment]
In my case this was being thrown because of the User.findOrCreate logic that I didn't even had defined. Facebook token passport package throws an internal server error because of that but the google one would just silently fail with no message. 

I will define my findOrCreate logic later down the development process. For now, this works for testing: 

```passport.use(
  new GoogleTokenStrategy(
    {
      clientID: config.get('google.clientID'),
      clientSecret: config.get('google.clientSecret')
    },
    function(accessToken, refreshToken, profile, done) {
      return done(null, profile);
    }
  )
);```

**Comment by robertdimarco** [comment]
Hey folks - Just FYI that this repo hasn't been active in a long time, and I'd love to hand it off. If anyone is interested in taking over, let me know! Otherwise I'll likely archive in the near future. Thanks.
