### ISSUE TITLE
Fresh Google Oauth2 and 401 error.

### ISSUE THREAD

**Issue by ronyrun** [robertdimarco/passport-google-token#7]
Hello,
I got an acces_token from my android Application like 

{"email":*********@gmail.com","userId":"********************","displayName":"***************","gender":"male","imageUrl":"https://lh3.googleusercontent.com/-**************************/x4oPC0*****/photo.jpg?sz=50","givenName":"************","familyName":"*************","ageRangeMin":21,"oauthToken":"***********************************"}

And I created an Oauth2 account on google : 
![image](https://cloud.githubusercontent.com/assets/7273443/9872525/25e854ca-5b9a-11e5-949b-c73314bda787.png)

Unfortunately when I declare the 
   clientID: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_CLIENT_SECRET

and add the "oauthToken" I have a 401 error
Would you tell me if this behavior is normal and tell me what I missed ?

Thank you very much.

**Comment by oreporan** [comment]
What was the solution?

**Comment by ronycohen** [comment]
I didn't find a solution

**Comment by oreporan** [comment]
I found a solution, not sure if its the same problem.
You're getting a 401 when you're sending your token to the backend?

**Comment by sebastiangug** [comment]
@oreporan  would've been nice to actually post your solution here even if it wasn't the same problem
